# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('dependent_type', models.CharField(choices=[('Wife', 'Wife'), ('Husband', 'Husband'), ('Child', 'Child')], max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('annual_salary', models.DecimalField(decimal_places=2, default=52000, max_digits=12)),
                ('benefit_cost', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dependent',
            name='employee_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='benefits.Employee'),
        ),
    ]
